//
//  OTLanguageTags.swift
//
//  Created by Muthu Nedumaran on 28/2/21.
//

//  Taken from : https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags

import Foundation

struct OTLanguageTags {
    let languages:[String: String] = [
        "ABA" : "Abaza",
        "ABK" : "Abkhazian",
        "ACH" : "Acholi",
        "ACR" : "Achi",
        "ADY" : "Adyghe",
        "AFK" : "Afrikaans",
        "AFR" : "Afar",
        "AGW" : "Agaw",
        "AIO" : "Aiton",
        "AKA" : "Akan",
        "AKB" : "Batak Angkola",
        "ALS" : "Alsatian",
        "ALT" : "Altai",
        "AMH" : "Amharic",
        "ANG" : "Anglo-Saxon",
        "ARA" : "Arabic",
        "ARG" : "Aragonese",
        "ARI" : "Aari",
        "ARK" : "Rakhine",
        "ASM" : "Assamese",
        "AST" : "Asturian",
        "ATH" : "Athapaskan languages",
        "AVR" : "Avar",
        "AWA" : "Awadhi",
        "AYM" : "Aymara",
        "AZB" : "Torki",
        "AZE" : "Azerbaijani",
        "BAD" : "Badaga",
        "BAG" : "Baghelkhandi",
        "BAL" : "Balkar",
        "BAN" : "Balinese",
        "BAR" : "Bavarian",
        "BAU" : "Baulé",
        "BBC" : "Batak Toba",
        "BBR" : "Berber",
        "BCH" : "Bench",
        "BCR" : "Bible Cree",
        "BDY" : "Bandjalang",
        "BEL" : "Belarussian",
        "BEM" : "Bemba",
        "BEN" : "Bengali",
        "BGC" : "Haryanvi",
        "BGQ" : "Bagri",
        "BGR" : "Bulgarian",
        "BHI" : "Bhili",
        "BHO" : "Bhojpuri",
        "BIK" : "Bikol",
        "BIL" : "Bilen",
        "BIS" : "Bislama",
        "BJJ" : "Kanauji",
        "BKF" : "Blackfoot",
        "BLI" : "Baluchi",
        "BLK" : "Pa’o Karen",
        "BLN" : "Balante",
        "BLT" : "Balti",
        "BMB" : "Bambara (Bamanankan)",
        "BML" : "Bamileke",
        "BOS" : "Bosnian",
        "BPY" : "Bishnupriya Manipuri",
        "BRE" : "Breton",
        "BRH" : "Brahui",
        "BRI" : "Braj Bhasha",
        "BRM" : "Burmese",
        "BRX" : "Bodo",
        "BSH" : "Bashkir",
        "BSK" : "Burushaski",
        "BTD" : "Batak Dairi (Pakpak)",
        "BTI" : "Beti",
        "BTK" : "Batak languages",
        "BTM" : "Batak Mandailing",
        "BTS" : "Batak Simalungun",
        "BTX" : "Batak Karo",
        "BTZ" : "Batak Alas-Kluet",
        "BUG" : "Bugis",
        "BYV" : "Medumba",
        "CAK" : "Kaqchikel",
        "CAT" : "Catalan",
        "CBK" : "Zamboanga Chavacano",
        "CEB" : "Cebuano",
        "CGG" : "Chiga",
        "CHA" : "Chamorro",
        "CHE" : "Chechen",
        "CHG" : "Chaha Gurage",
        "CHH" : "Chattisgarhi",
        "CHI" : "Chichewa (Chewa, Nyanja)",
        "CHK" : "Chukchi",
        "CHO" : "Choctaw",
        "CHP" : "Chipewyan",
        "CHR" : "Cherokee",
        "CHU" : "Chuvash",
        "CHY" : "Cheyenne",
        "CJA" : "Western Cham",
        "CJM" : "Eastern Cham",
        "CMR" : "Comorian",
        "COP" : "Coptic",
        "COR" : "Cornish",
        "COS" : "Corsican",
        "CPP" : "Creoles",
        "CRE" : "Cree",
        "CRR" : "Carrier",
        "CRT" : "Crimean Tatar",
        "CSB" : "Kashubian",
        "CSL" : "Church Slavonic",
        "CSY" : "Czech",
        "CTG" : "Chittagonian",
        "CUK" : "San Blas Kuna",
        "DAG" : "Dagbani",
        "DAN" : "Danish",
        "DAR" : "Dargwa",
        "DAX" : "Dayi",
        "DCR" : "Woods Cree",
        "DEU" : "German",
        "DGO" : "Dogri (individual language)",
        "DGR" : "Dogri (macrolanguage)",
        "DHG" : "Dhangu",
        "DHV" : "Divehi (Dhivehi, Maldivian)",
        "DIQ" : "Dimli",
        "DIV" : "Divehi (Dhivehi, Maldivian)",
        "DJR" : "Zarma",
        "DNG" : "Dangme",
        "DNJ" : "Dan",
        "DNK" : "Dinka",
        "DRI" : "Dari",
        "DUJ" : "Dhuwal",
        "DUN" : "Dungan",
        "DZN" : "Dzongkha",
        "EBI" : "Ebira",
        "ECR" : "Eastern Cree",
        "EDO" : "Edo",
        "EFI" : "Efik",
        "ELL" : "Greek",
        "EMK" : "Eastern Maninkakan",
        "ENG" : "English",
        "ERZ" : "Erzya",
        "ESP" : "Spanish",
        "ESU" : "Central Yupik",
        "ETI" : "Estonian",
        "EUQ" : "Basque",
        "EVK" : "Evenki",
        "EVN" : "Even",
        "EWE" : "Ewe",
        "FAN" : "French Antillean",
        "FAR" : "Persian",
        "FAT" : "Fanti",
        "FIN" : "Finnish",
        "FJI" : "Fijian",
        "FLE" : "Dutch (Flemish)",
        "FMP" : "Fe’fe’",
        "FNE" : "Forest Enets",
        "FON" : "Fon",
        "FOS" : "Faroese",
        "FRA" : "French",
        "FRC" : "Cajun French",
        "FRI" : "Frisian",
        "FRL" : "Friulian",
        "FRP" : "Arpitan",
        "FTA" : "Futa",
        "FUL" : "Fulah",
        "FUV" : "Nigerian Fulfulde",
        "GAD" : "Ga",
        "GAE" : "Scottish Gaelic (Gaelic)",
        "GAG" : "Gagauz",
        "GAL" : "Galician",
        "GAR" : "Garshuni",
        "GAW" : "Garhwali",
        "GEZ" : "Geez",
        "GIH" : "Githabul",
        "GIL" : "Gilyak",
        "GKP" : "Kpelle (Guinea)",
        "GLK" : "Gilaki",
        "GMZ" : "Gumuz",
        "GNN" : "Gumatj",
        "GOG" : "Gogo",
        "GON" : "Gondi",
        "GRN" : "Greenlandic",
        "GRO" : "Garo",
        "GUA" : "Guarani",
        "GUC" : "Wayuu",
        "GUF" : "Gupapuyngu",
        "GUJ" : "Gujarati",
        "GUZ" : "Gusii",
        "HAI" : "Haitian (Haitian Creole)",
        "HAL" : "Halam (Falam Chin)",
        "HAR" : "Harauti",
        "HAU" : "Hausa",
        "HAW" : "Hawaiian",
        "HAY" : "Haya",
        "HAZ" : "Hazaragi",
        "HBN" : "Hammer-Banna",
        "HER" : "Herero",
        "HIL" : "Hiligaynon",
        "HIN" : "Hindi",
        "HMA" : "High Mari",
        "HMN" : "Hmong",
        "HMO" : "Hiri Motu",
        "HND" : "Hindko",
        "HO" : "Ho",
        "HRI" : "Harari",
        "HRV" : "Croatian",
        "HUN" : "Hungarian",
        "HYE" : "Armenian",
        "IBA" : "Iban",
        "IBB" : "Ibibio",
        "IBO" : "Igbo",
        "IDO" : "Ido",
        "IJO" : "Ijo languages",
        "ILE" : "Interlingue",
        "ILO" : "Ilokano",
        "INA" : "Interlingua",
        "IND" : "Indonesian",
        "ING" : "Ingush",
        "INU" : "Inuktitut",
        "IPK" : "Inupiat",
        "IRI" : "Irish",
        "IRT" : "Irish Traditional",
        "ISL" : "Icelandic",
        "ISM" : "Inari Sami",
        "ITA" : "Italian",
        "IWR" : "Hebrew",
        "JAM" : "Jamaican Creole",
        "JAN" : "Japanese",
        "JAV" : "Javanese",
        "JBO" : "Lojban",
        "JCT" : "Krymchak",
        "JII" : "Yiddish",
        "JUD" : "Ladino",
        "JUL" : "Jula",
        "KAB" : "Kabardian",
        "KAC" : "Kachchi",
        "KAL" : "Kalenjin",
        "KAN" : "Kannada",
        "KAR" : "Karachay",
        "KAT" : "Georgian",
        "KAZ" : "Kazakh",
        "KDE" : "Makonde",
        "KEA" : "Kabuverdianu (Crioulo)",
        "KEB" : "Kebena",
        "KEK" : "Kekchi",
        "KGE" : "Khutsuri Georgian",
        "KHA" : "Khakass",
        "KHK" : "Khanty-Kazim",
        "KHM" : "Khmer",
        "KHS" : "Khanty-Shurishkar",
        "KHT" : "Khamti Shan",
        "KHV" : "Khanty-Vakhi",
        "KHW" : "Khowar",
        "KIK" : "Kikuyu (Gikuyu)",
        "KIR" : "Kirghiz (Kyrgyz)",
        "KIS" : "Kisii",
        "KIU" : "Kirmanjki",
        "KJD" : "Southern Kiwai",
        "KJP" : "Eastern Pwo Karen",
        "KJZ" : "Bumthangkha",
        "KKN" : "Kokni",
        "KLM" : "Kalmyk",
        "KMB" : "Kamba",
        "KMN" : "Kumaoni",
        "KMO" : "Komo",
        "KMS" : "Komso",
        "KMZ" : "Khorasani Turkic",
        "KNR" : "Kanuri",
        "KOD" : "Kodagu",
        "KOH" : "Korean Old Hangul",
        "KOK" : "Konkani",
        "KOM" : "Komi",
        "KON" : "Kikongo",
        "KOP" : "Komi-Permyak",
        "KOR" : "Korean",
        "KOS" : "Kosraean",
        "KOZ" : "Komi-Zyrian",
        "KPL" : "Kpelle",
        "KRI" : "Krio",
        "KRK" : "Karakalpak",
        "KRL" : "Karelian",
        "KRM" : "Karaim",
        "KRN" : "Karen",
        "KRT" : "Koorete",
        "KSH" : "Kashmiri",
        "KSI" : "Khasi",
        "KSM" : "Kildin Sami",
        "KSW" : "S’gaw Karen",
        "KUA" : "Kuanyama",
        "KUI" : "Kui",
        "KUL" : "Kulvi",
        "KUM" : "Kumyk",
        "KUR" : "Kurdish",
        "KUU" : "Kurukh",
        "KUY" : "Kuy",
        "KYK" : "Koryak",
        "KYU" : "Western Kayah",
        "LAD" : "Ladin",
        "LAH" : "Lahuli",
        "LAK" : "Lak",
        "LAM" : "Lambani",
        "LAO" : "Lao",
        "LAT" : "Latin",
        "LAZ" : "Laz",
        "LCR" : "L-Cree",
        "LDK" : "Ladakhi",
        "LEZ" : "Lezgi",
        "LIJ" : "Ligurian",
        "LIM" : "Limburgish",
        "LIN" : "Lingala",
        "LIS" : "Lisu",
        "LJP" : "Lampung",
        "LKI" : "Laki",
        "LMA" : "Low Mari",
        "LMB" : "Limbu",
        "LMO" : "Lombard",
        "LMW" : "Lomwe",
        "LOM" : "Loma",
        "LRC" : "Luri",
        "LSB" : "Lower Sorbian",
        "LSM" : "Lule Sami",
        "LTH" : "Lithuanian",
        "LTZ" : "Luxembourgish",
        "LUA" : "Luba-Lulua",
        "LUB" : "Luba-Katanga",
        "LUG" : "Ganda",
        "LUH" : "Luyia",
        "LUO" : "Luo",
        "LVI" : "Latvian",
        "MAD" : "Madura",
        "MAG" : "Magahi",
        "MAH" : "Marshallese",
        "MAJ" : "Majang",
        "MAK" : "Makhuwa",
        "MAL" : "Malayalam",
        "MAM" : "Mam",
        "MAN" : "Mansi",
        "MAP" : "Mapudungun",
        "MAR" : "Marathi",
        "MAW" : "Marwari",
        "MBN" : "Mbundu",
        "MBO" : "Mbo",
        "MCH" : "Manchu",
        "MCR" : "Moose Cree",
        "MDE" : "Mende",
        "MDR" : "Mandar",
        "MEN" : "Me’en",
        "MER" : "Meru",
        "MFA" : "Pattani Malay",
        "MFE" : "Morisyen",
        "MIN" : "Minangkabau",
        "MIZ" : "Mizo",
        "MKD" : "Macedonian",
        "MKR" : "Makasar",
        "MKW" : "Kituba",
        "MLE" : "Male",
        "MLG" : "Malagasy",
        "MLN" : "Malinke",
        "MLR" : "Malayalam Reformed",
        "MLY" : "Malay",
        "MND" : "Mandinka",
        "MNG" : "Mongolian",
        "MNI" : "Manipuri",
        "MNK" : "Maninka",
        "MNX" : "Manx",
        "MOH" : "Mohawk", 
        "MOK" : "Moksha",
        "MOL" : "Moldavian",
        "MON" : "Mon",
        "MOR" : "Moroccan",
        "MOS" : "Mossi",
        "MRI" : "Maori",
        "MTH" : "Maithili",
        "MTS" : "Maltese",
        "MUN" : "Mundari",
        "MUS" : "Muscogee",
        "MWL" : "Mirandese",
        "MWW" : "Hmong Daw",
        "MYN" : "Mayan",
        "MZN" : "Mazanderani",
        "NAG" : "Naga-Assamese",
        "NAH" : "Nahuatl",
        "NAN" : "Nanai",
        "NAP" : "Neapolitan",
        "NAS" : "Naskapi",
        "NAU" : "Nauruan",
        "NAV" : "Navajo",
        "NCR" : "N-Cree",
        "NDB" : "Ndebele",
        "NDC" : "Ndau",
        "NDG" : "Ndonga",
        "NDS" : "Low Saxon",
        "NEP" : "Nepali",
        "NEW" : "Newari",
        "NGA" : "Ngbaka",
        "NGR" : "Nagari",
        "NHC" : "Norway House Cree",
        "NIS" : "Nisi",
        "NIU" : "Niuean",
        "NKL" : "Nyankole",
        "NKO" : "N’Ko",
        "NLD" : "Dutch",
        "NOE" : "Nimadi",
        "NOG" : "Nogai",
        "NOR" : "Norwegian",
        "NOV" : "Novial",
        "NSM" : "Northern Sami",
        "NSO" : "Northern Sotho",
        "NTA" : "Northern Tai",
        "NTO" : "Esperanto",
        "NYM" : "Nyamwezi",
        "NYN" : "Norwegian Nynorsk (Nynorsk, Norwegian)",
        "NZA" : "Mbembe Tigon",
        "OCI" : "Occitan",
        "OCR" : "Oji-Cree",
        "OJB" : "Ojibway",
        "ORI" : "Odia (formerly Oriya)",
        "ORO" : "Oromo",
        "OSS" : "Ossetian",
        "PAA" : "Palestinian Aramaic",
        "PAG" : "Pangasinan",
        "PAL" : "Pali",
        "PAM" : "Pampangan",
        "PAN" : "Punjabi",
        "PAP" : "Palpa",
        "PAS" : "Pashto",
        "PAU" : "Palauan",
        "PCC" : "Bouyei",
        "PCD" : "Picard",
        "PDC" : "Pennsylvania German",
        "PGR" : "Polytonic Greek",
        "PHK" : "Phake",
        "PIH" : "Norfolk",
        "PIL" : "Filipino",
        "PLG" : "Palaung",
        "PLK" : "Polish",
        "PMS" : "Piemontese",
        "PNB" : "Western Panjabi",
        "POH" : "Pocomchi",
        "PON" : "Pohnpeian",
        "PRO" : "Provençal / Old Provençal",
        "PTG" : "Portuguese",
        "PWO" : "Western Pwo Karen",
        "QIN" : "Chin",
        "QUC" : "K’iche’",
        "QUH" : "Quechua (Bolivia)",
        "QUZ" : "Quechua",
        "QVI" : "Quechua (Ecuador)",
        "QWH" : "Quechua (Peru)",
        "RAJ" : "Rajasthani",
        "RAR" : "Rarotongan",
        "RBU" : "Russian Buriat",
        "RCR" : "R-Cree",
        "REJ" : "Rejang",
        "RIA" : "Riang",
        "RIF" : "Tarifit",
        "RIT" : "Ritarungo",
        "RKW" : "Arakwal",
        "RMS" : "Romansh",
        "RMY" : "Vlax Romani",
        "ROM" : "Romanian",
        "ROY" : "Romany",
        "RSY" : "Rusyn",
        "RTM" : "Rotuman",
        "RUA" : "Kinyarwanda",
        "RUN" : "Rundi",
        "RUP" : "Aromanian",
        "RUS" : "Russian",
        "SAD" : "Sadri",
        "SAN" : "Sanskrit",
        "SAS" : "Sasak",
        "SAT" : "Santali",
        "SAY" : "Sayisi",
        "SCN" : "Sicilian",
        "SCO" : "Scots",
        "SCS" : "North Slavey",
        "SEK" : "Sekota",
        "SEL" : "Selkup",
        "SGA" : "Old Irish",
        "SGO" : "Sango",
        "SGS" : "Samogitian",
        "SHI" : "Tachelhit",
        "SHN" : "Shan",
        "SIB" : "Sibe",
        "SID" : "Sidamo",
        "SIG" : "Silte Gurage",
        "SKS" : "Skolt Sami",
        "SKY" : "Slovak",
        "SLA" : "Slavey",
        "SLV" : "Slovenian",
        "SML" : "Somali",
        "SMO" : "Samoan",
        "SNA" : "Sena",
        "SND" : "Sindhi",
        "SNH" : "Sinhala (Sinhalese)",
        "SNK" : "Soninke",
        "SOG" : "Sodo Gurage",
        "SOP" : "Songe",
        "SOT" : "Southern Sotho",
        "SQI" : "Albanian",
        "SRB" : "Serbian",
        "SRD" : "Sardinian",
        "SRK" : "Saraiki",
        "SRR" : "Serer",
        "SSL" : "South Slavey",
        "SSM" : "Southern Sami",
        "STQ" : "Saterland Frisian",
        "SUK" : "Sukuma",
        "SUN" : "Sundanese",
        "SUR" : "Suri",
        "SVA" : "Svan",
        "SVE" : "Swedish",
        "SWA" : "Swadaya Aramaic",
        "SWK" : "Swahili",
        "SWZ" : "Swati",
        "SXT" : "Sutu",
        "SXU" : "Upper Saxon",
        "SYL" : "Sylheti",
        "SYR" : "Syriac",
        "Syre" : "Syriac, Estrangela script-variant (equivalent to ISO 15924",
        "Syrj" : "Syriac, Western script-variant (equivalent to ISO 15924",
        "Syrn" : "Syriac, Eastern script-variant (equivalent to ISO 15924",
        "SZL" : "Silesian",
        "TAB" : "Tabasaran",
        "TAJ" : "Tajiki",
        "TAM" : "Tamil",
        "TAT" : "Tatar",
        "TCR" : "TH-Cree",
        "TDD" : "Dehong Dai",
        "TEL" : "Telugu",
        "TET" : "Tetum",
        "TGL" : "Tagalog",
        "TGN" : "Tongan",
        "TGR" : "Tigre",
        "TGY" : "Tigrinya",
        "THA" : "Thai",
        "THT" : "Tahitian",
        "TIB" : "Tibetan",
        "TIV" : "Tiv",
        "TKM" : "Turkmen",
        "TMH" : "Tamashek",
        "TMN" : "Temne",
        "TNA" : "Tswana",
        "TNE" : "Tundra Enets",
        "TNG" : "Tonga",
        "TOD" : "Todo",
        "TPI" : "Tok Pisin",
        "TRK" : "Turkish",
        "TSG" : "Tsonga",
        "TSJ" : "Tshangla",
        "TUA" : "Turoyo Aramaic",
        "TUL" : "Tumbuka",
        "TUM" : "Tulu",
        "TUV" : "Tuvin",
        "TVL" : "Tuvalu",
        "TWI" : "Twi",
        "TYZ" : "Tày",
        "TZM" : "Tamazight",
        "TZO" : "Tzotzil",
        "UDM" : "Udmurt",
        "UKR" : "Ukrainian",
        "UMB" : "Umbundu",
        "URD" : "Urdu",
        "USB" : "Upper Sorbian",
        "UYG" : "Uyghur",
        "UZB" : "Uzbek",
        "VEC" : "Venetian",
        "VEN" : "Venda",
        "VIT" : "Vietnamese",
        "VOL" : "Volapük",
        "VRO" : "Võro",
        "WA" : "Wa",
        "WAG" : "Wagdi",
        "WAR" : "Waray-Waray",
        "WCR" : "West-Cree",
        "WEL" : "Welsh",
        "WLF" : "Wolof",
        "WLN" : "Walloon",
        "WTM" : "Mewati",
        "XBD" : "Lü",
        "XHS" : "Xhosa",
        "XJB" : "Minjangbal",
        "XKF" : "Khengkha",
        "XOG" : "Soga",
        "XPE" : "Kpelle (Liberia)",
        "YAK" : "Sakha",
        "YAO" : "Yao",
        "YAP" : "Yapese",
        "YBA" : "Yoruba",
        "YCR" : "Y-Cree",
        "YIC" : "Yi Classic",
        "YIM" : "Yi Modern",
        "ZEA" : "Zealandic",
        "ZGH" : "Standard Moroccan Tamazight",
        "ZHA" : "Zhuang",
        "ZHH" : "Chinese, Traditional, Hong Kong SAR",
        "ZHP" : "Chinese, Phonetic",
        "ZHS" : "Chinese, Simplified",
        "ZHT" : "Chinese, Traditional",
        "ZHTM" : "Chinese, Traditional, Macao SAR",
        "ZND" : "Zande",
        "ZUL" : "Zulu",
        "ZZA" : "Zazaki"
    ]
}
